import React, { useState } from 'react'
import LoginPage from '../pages/LoginPage'
import Card from '@material-ui/core/Card'
import { makeStyles } from '@material-ui/core/styles'
import Button from '@material-ui/core/Button'
// react component that copies the given text inside your clipboard
import { CopyToClipboard } from 'react-copy-to-clipboard'
import CodeIcon from '@material-ui/icons/Code'
import FacebookIcon from '@material-ui/icons/Facebook'
import TwitterIcon from '@material-ui/icons/Twitter'
import MailIcon from '@material-ui/icons/Mail'
import Box from '@material-ui/core/Box'
import Grid from '@material-ui/core/Grid'
import Tooltip from '@material-ui/core/Tooltip'

const useStyles = makeStyles(theme => ({
  root1: {
    display: 'flex',
    flexWrap: 'wrap',
    '& > *': {
      margin: theme.spacing(1.5),
      width: theme.spacing(4),
      height: theme.spacing(16)
    }
  },
  paper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 310
  },
  media: {
    height: 0,
    paddingTop: '56.25%' // 16:9
  },
  expand: {
    transform: 'rotate(0deg)',
    marginLeft: 'auto',
    transition: theme.transitions.create('transform', {
      duration: theme.transitions.duration.shortest
    })
  },
  expandOpen: {
    transform: 'rotate(180deg)'
  },
  content: {
  },
  btnheader: {
    width: '100%',
    height: '50px',
    color: 'black',
    fontWeight: 'bold',
    marginBottom: '10px',
    backgroundColor: 'black',
  }
}))

const Referrals = () => {
  const classes = useStyles()
  const [copiedText, setCopiedText] = useState()
  return (
    <div>
      <LoginPage />
      <div className='container-fluid mb-5'>
        <div className='row'>
          <div className='col-11 mx-auto'>
            <div className='row gy-6' id='blogcontent_type'>
              <Card className={classes.root}>
                <h5 className='my-3 font-weight-bold'>Give 20,get paid</h5>
                <p className=''>
                  Give $20 in credits when someone signs up using your referral
                  link. You will earn 30% of the revenue generated by that user
                  for the next year.
                </p>
                <Button
                  className={classes.btnheader}
                  variant='outlined'
                  color='primary'
                  style={{ textTransform: 'none' }}
                >
                  Add referral link to link block
                </Button>
                {/* <br /> */}
                <Button
                  className={classes.btnheader}
                  variant='outlined'
                  color='primary'
                  style={{ textTransform: 'none' }}
                >
                  Generate Page for a friend
                </Button>
                <Grid
                  item
                  component={Box}
                >
                  <CopyToClipboard
                    text={'ni ni-active-40'}
                    onCopy={() => setCopiedText('ni ni-active-40')}
                  >
                    <Tooltip
                      title={
                        copiedText === 'ni ni-active-40'
                          ? 'This was Copied!'
                          : 'Copy To Clipboard'
                      }
                      placement='top'
                    >
                      <Box
                        component='button'
                        fontFamily='inherit'
                        fontSize='16px'
                        fontWeight='400'
                        lineHeight='1.0'
                        display='inline-block'
                        width='100%'
                        margin='.5rem 0'
                        padding='24px'
                        textAlign='center'
                        border='0'
                        borderRadius='4px'
                        data-clipboard-text='album-2'
                        type='button'
                      >
                        <div>
                          <span className='mx-2'>
                            https://beacons.ai/signup?c=kaltabg
                          </span>
                          <CodeIcon />
                        </div>
                      </Box>
                    </Tooltip>
                  </CopyToClipboard>
                </Grid>

                <br />
                <h6 className='font-weight-bold'>Share via</h6>
                <div className='d-flex justify-content-center align-content-center my-2 py-2'>
                  <FacebookIcon
                    style={{
                      border: '2px solid black',
                      fontSize: '50px',
                      borderRadius: '50%',
                      padding: '5px 6px',
                      margin: '0 5px'
                    }}
                  />
                  <TwitterIcon
                    style={{
                      border: '2px solid black',
                      fontSize: '50px',
                      borderRadius: '50%',
                      padding: '5px 6px',
                      margin: '0 5px'
                    }}
                  />
                  <MailIcon
                    style={{
                      border: '2px solid black',
                      fontSize: '50px',
                      borderRadius: '50%',
                      padding: '5px 6px',
                      margin: '0 5px'
                    }}
                  />
                </div>
                <h6 className='font-weight-bold'>
                  <strong>What to say</strong>
                </h6>
                <p className=''>
                  You know your audience best, but here is one strategy that has
                  worked on Instagram.
                  <u>
                    Check out the @beacons.ai Instagram highlight reels for some
                    examples.
                  </u>
                </p>
                {/* <ol> */}
                {/* <> */}
                <li className=''>
                  Make a story post with your Beacons page that swipes up to
                  your Beacons referral link. Alternatively, you can also swap
                  out your bio link for your Beacons referral link.
                </li>
                <li className=''>Write/say something along the lines of</li>
                <div className='px-3 py-3 my-2' style={{backgroundColor:"rgb(238,238,238)",borderRadius:"5px"}}>
                  The bio link I am using finally opened up signups. If you have
                  a TikTok or an Instagram account, it takes 30 seconds to set
                  up. And it comes with a ton of features for customization and
                  monetization. Use my referral link to get $20 of credit. Swipe
                  up! @beacons.ai
                </div>
                <h6 className="font-weight-bold">Referred users</h6>
                <p className="">Users you prefer will show up here after they sign up using your link.</p>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Referrals
